#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Report/Index.cshtml")]
    public partial class _Views_Report_Index_cshtml : System.Web.Mvc.WebViewPage<KruisIT.Web.Analytics.Models.CurrentList<string>>
    {
        public _Views_Report_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Report\Index.cshtml"
  
	ViewBag.Title = "Analytics";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 119), Tuple.Create("\"", 162)
            
            #line 6 "..\..\Views\Report\Index.cshtml"
, Tuple.Create(Tuple.Create("", 126), Tuple.Create<System.Object, System.Int32>(ViewBag.Url
            
            #line default
            #line hidden
, 126), false)
, Tuple.Create(Tuple.Create("", 140), Tuple.Create("Resource/analytics_css", 140), true)
);

WriteLiteral(">\r\n\r\n<div");

WriteLiteral(" class=\"analytics-block\"");

WriteLiteral(">\r\n\t<h2>\r\n");

WriteLiteral("\t\t");

            
            #line 10 "..\..\Views\Report\Index.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t<small>\r\n");

            
            #line 12 "..\..\Views\Report\Index.cshtml"
			
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Report\Index.cshtml"
             if (!String.IsNullOrEmpty(Model.Filter.Website)) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("Website: ");

            
            #line 12 "..\..\Views\Report\Index.cshtml"
                                                                          Write(Model.Filter.Website);

            
            #line default
            #line hidden
WriteLiteral(" ,");

WriteLiteral(" ");

            
            #line 12 "..\..\Views\Report\Index.cshtml"
                                                                                                              }

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

            
            #line 13 "..\..\Views\Report\Index.cshtml"
             if (!String.IsNullOrEmpty(Model.Filter.Location)) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("Location: ");

            
            #line 13 "..\..\Views\Report\Index.cshtml"
                                                                            Write(Model.Filter.Location);

            
            #line default
            #line hidden
WriteLiteral(" ,");

WriteLiteral(" ");

            
            #line 13 "..\..\Views\Report\Index.cshtml"
                                                                                                                 }

            
            #line default
            #line hidden
WriteLiteral("\t\t\t");

            
            #line 14 "..\..\Views\Report\Index.cshtml"
             if (!String.IsNullOrEmpty(Model.Filter.Visitor)) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral("Visitor: ");

            
            #line 14 "..\..\Views\Report\Index.cshtml"
                                                                          Write(Model.Filter.Visitor);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 14 "..\..\Views\Report\Index.cshtml"
                                                                                                            }

            
            #line default
            #line hidden
WriteLiteral("\t\t</small>\r\n\t</h2>\r\n\r\n");

            
            #line 18 "..\..\Views\Report\Index.cshtml"
	
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Report\Index.cshtml"
     foreach (var site in Model.Data)
	{
		
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Report\Index.cshtml"
   Write(Html.Action("Website", new { website = site, location = Model.Filter.Location, visitor = Model.Filter.Visitor }));

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Report\Index.cshtml"
                                                                                                                         
	}

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
