#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Report/Index.cshtml")]
    public partial class _Views_Report_Index_cshtml : System.Web.Mvc.WebViewPage<KruisIT.Web.Analytics.Models.CurrentList<string>>
    {
        public _Views_Report_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Report\Index.cshtml"
  
	ViewBag.Title = "Analytics";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 119), Tuple.Create("\"", 162)
            
            #line 6 "..\..\Views\Report\Index.cshtml"
, Tuple.Create(Tuple.Create("", 126), Tuple.Create<System.Object, System.Int32>(ViewBag.Url
            
            #line default
            #line hidden
, 126), false)
, Tuple.Create(Tuple.Create("", 140), Tuple.Create("Resource/analytics_css", 140), true)
);

WriteLiteral(" />\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 198), Tuple.Create("\"", 239)
            
            #line 7 "..\..\Views\Report\Index.cshtml"
, Tuple.Create(Tuple.Create("", 204), Tuple.Create<System.Object, System.Int32>(ViewBag.Url
            
            #line default
            #line hidden
, 204), false)
, Tuple.Create(Tuple.Create("", 218), Tuple.Create("Resource/analytics_js", 218), true)
);

WriteLiteral("></script>\r\n\r\n<div");

WriteLiteral(" class=\"analytics-menu\"");

WriteLiteral(">\r\n\t<h2>\r\n");

WriteLiteral("\t\t");

            
            #line 11 "..\..\Views\Report\Index.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t<small>\r\n");

WriteLiteral("\t\t\t");

            
            #line 13 "..\..\Views\Report\Index.cshtml"
       Write(Model.Filter.StartDate.Value.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("<br />-<br />\r\n");

WriteLiteral("\t\t\t");

            
            #line 14 "..\..\Views\Report\Index.cshtml"
       Write(Model.Filter.EndDate.Value.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 15 "..\..\Views\Report\Index.cshtml"
			
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Report\Index.cshtml"
             if (!String.IsNullOrEmpty(Model.Filter.Location))
			{
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(", Location: ");

            
            #line 16 "..\..\Views\Report\Index.cshtml"
                           Write(Model.Filter.Location);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 16 "..\..\Views\Report\Index.cshtml"
                                                              }

            
            #line default
            #line hidden
WriteLiteral("\t\t</small>\r\n\t</h2>\r\n\r\n");

            
            #line 20 "..\..\Views\Report\Index.cshtml"
	
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Report\Index.cshtml"
     if (Model.Data.Any())
	{
		if (Model.Data.Count > 1)
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<select");

WriteLiteral(" id=\"analytics-select-website\"");

WriteLiteral(">\r\n");

            
            #line 25 "..\..\Views\Report\Index.cshtml"
				
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Report\Index.cshtml"
                 foreach (var site in Model.Data)
				{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t<option>");

            
            #line 27 "..\..\Views\Report\Index.cshtml"
                       Write(site);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 28 "..\..\Views\Report\Index.cshtml"
				}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t</select>\r\n");

            
            #line 30 "..\..\Views\Report\Index.cshtml"
		}
		else
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<div>");

            
            #line 33 "..\..\Views\Report\Index.cshtml"
            Write(Model.Data.First());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 34 "..\..\Views\Report\Index.cshtml"
		}
	}
	else
	{

            
            #line default
            #line hidden
WriteLiteral("\t\t<div>No Website</div>\r\n");

            
            #line 39 "..\..\Views\Report\Index.cshtml"
	}

            
            #line default
            #line hidden
WriteLiteral("\r\n\t<ul");

WriteLiteral(" id=\"analytics-select-view\"");

WriteLiteral(">\r\n\t\t<li><input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"view\"");

WriteLiteral(" id=\"vwVisits\"");

WriteLiteral(" value=\"Aggregates_Visits\"");

WriteLiteral(" checked=\"checked\"");

WriteLiteral(" /><label");

WriteLiteral(" for=\"vwVisits\"");

WriteLiteral(">Page views</label></li>\r\n\t\t<li><input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"view\"");

WriteLiteral(" id=\"vwVisitors\"");

WriteLiteral(" value=\"Aggregates_Visitors\"");

WriteLiteral(" /><label");

WriteLiteral(" for=\"vwVisitors\"");

WriteLiteral(">Visitors</label></li>\r\n\t\t<li><input");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" name=\"view\"");

WriteLiteral(" id=\"vwMostViewed\"");

WriteLiteral(" value=\"MostViewed\"");

WriteLiteral(" /><label");

WriteLiteral(" for=\"vwMostViewed\"");

WriteLiteral(">Most viewed</label></li>\r\n\t</ul>\r\n\r\n\t<div");

WriteLiteral(" id=\"analytics-base-url\"");

WriteLiteral(">");

            
            #line 47 "..\..\Views\Report\Index.cshtml"
                             Write(ViewBag.Url);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"analytics-block\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" id=\"analytics-data\"");

WriteLiteral("></div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
