#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Report/Visitors.cshtml")]
    public partial class _Views_Report_Visitors_cshtml : System.Web.Mvc.WebViewPage<KruisIT.Web.Analytics.Models.CurrentList<KruisIT.Web.Analytics.Models.Visitor>>
    {
        public _Views_Report_Visitors_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Report\Visitors.cshtml"
  
	Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"analytics-visitors\"");

WriteLiteral(">\r\n\t<h4>");

            
            #line 7 "..\..\Views\Report\Visitors.cshtml"
   Write(Model.Data.Count);

            
            #line default
            #line hidden
WriteLiteral(" Visitors</h4>\r\n\r\n\t<ul>\r\n");

            
            #line 10 "..\..\Views\Report\Visitors.cshtml"
		
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Report\Visitors.cshtml"
         foreach (var visitor in Model.Data)
		{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t<li>");

            
            #line 12 "..\..\Views\Report\Visitors.cshtml"
           Write(Html.ActionLink(visitor.Address, "Index", new { website = Model.Filter.Website, location = Model.Filter.Location, visitor = visitor.Address }, null));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");

            
            #line 13 "..\..\Views\Report\Visitors.cshtml"
		}

            
            #line default
            #line hidden
WriteLiteral("\t</ul>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
