// <auto-generated />
namespace KruisIT.Web.Analytics.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserAgent_Referrer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserAgent_Referrer));
        
        string IMigrationMetadata.Id
        {
            get { return "201604162030404_UserAgent_Referrer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
